version: '3.9'
services:

  postgres:
    image: postgres:16
    container_name: postgres_data_api
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm
      POSTGRES_DB: DataApi
    ports:
      - '5438:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_scripts/postgresql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:latest
    container_name: mongo_data_api
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
      - ./db_scripts/mongo:/docker-entrypoint-initdb.d

  model_orchestrator:
    build: ./ModelOrchestrator
    container_name: mo_data_api
    restart: always
    ports:
      - '8082:8082'
      - '11411:11411'
    depends_on:
      - postgres
      - mongo 

  source_manager:
    build: ./SourceManager
    container_name: sm_data_api
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - data_processor
    
  data_processor:
    build: ./DataProcessor
    container_name: dp_data_api
    restart: always
    ports:
      - '50051:50051'
    depends_on:
      - model_orchestrator