CREATE TABLE data_sources (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	connection_string TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ml_models (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	connection_string TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logs (
	id SERIAL PRIMARY KEY,
	source_id INTEGER[] NOT NULL,
	model_id INTEGER NOT NULL,
	time INTERVAL NOT NULL,
	time_with_response INTERVAL NOT NULL,
	status VARCHAR(10) NOT NULL ,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);